py_library(
    name = "init",
    srcs = [
        "__init__.py",
        "base.py",
        "base_dem.py",
        "per.py",
        "per_dem.py",
        "segment_tree.py",
    ],
    visibility = ["//visibility:public"],
)
